type: chart
envValues:
  - envVar: KUBECTL_VERSION
    value: v1.9.2
configs:
  - chart: vault-etcd
    timeout: 600
    retries: 2
    release: etcd
    test: 
      values:
        - key: service.tls.enable
          value: true
test:
  beforeScript:
    script: scripts/beforeTest.sh
    shell: /usr/local/bin/bash
stage:
  deploy: false
prod:
  doDeploy: none

 