component: "etcd"

rbac:
  create: true
  apiVersion: v1beta1

image:
  source: "quay.io/coreos/etcd"
  tag: "v3.2.10"
  pullPolicy: "Always"

service:
  name: etcdvault
  peerPort: 3380
  clientPort: 3379
  replicas: 3
  cpu: "100m"
  memory: "512Mi"
  dataDir: "/ephemeral"
  terminationGracePeriodSeconds: 30
  tls:
    enable: true
    serverSecret: etcd-server-tls
    peerSecret: etcd-peer-tls
    clientSecret: etcd-client-tls

nodeSelector: {}

storage:
  storageClass: "default"
  size: 1Gi
  mount: "ephemeral"
  accessModes:
    - ReadWriteOnce
