component: "etcd"

image:
  source: "quay.io/coreos/etcd"
  tag: "v3.2.9"
  pullPolicy: "Always"

service:
  name: etcdvault
  peerPort: 3380
  clientPort: 3379
  replicas: 3
  cpu: "100m"
  memory: "512Mi"
  dataDir: "/ephemeral"
  terminationGracePeriodSeconds: 30

Name: etcdvault
PeerPort: 3380
ClientPort: 3379
Component: "etcd"
Replicas: 3
Image: "quay.io/coreos/etcd"
ImageTag: "v3.2.9"
ImagePullPolicy: "Always"
Cpu: "100m"
Memory: "512Mi"
Storage: "1Gi"
DataDir: "/ephemeral"
VolumeMount: "ephemeral"

## etcd data Persistent Volume Storage Class
## If defined, StorageClassName: <storageClass>
## If set to "-", StorageClassName: "", which disables dynamic provisioning
## If undefined (the default) or set to null, no storageClassName spec is
##   set, choosing the default provisioner.  (gp2 on AWS, standard on
##   GKE, AWS & OpenStack)
##
# set to "default"
storage:
  storageClass: "default"
  size: 1Gi
  mount: "ephemeral"
  accessModes:
    - ReadWriteOnce
