---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "vault-etcd.fullname" . ) }}
  labels:
    app: {{ template "vault-etcd.name" .}}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: {{ .Values.service.peerPort }}
    name: etcd-server
  - port: {{ .Values.service.clientPort }}
    name: etcd-client
  clusterIP: None
  selector:
    app: {{ template "vault-etcd.name" .}}
    release: {{ .Release.Name }}
