{{- if .Values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.rbac.serviceAccountName }}
  labels:
    app: {{ template "vault-etcd.name" . }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- end }}